# https://forum.cursor.com/t/cursor-bundle-identifier/779
name = "Cursor"

[handlers.command]
file = "vscode.js"
args = ["/Applications/Cursor.app"]

[[import]]
file = "com/microsoft/VSCode/macos.toml"
